import type { Request, Response, NextFunction } from "express";
import { HttpException } from "@/utils/http.exception";

export function errorMiddleware(error: Error, req: Request, res: Response, next: NextFunction): void {
  let statusCode = 500;
  let message = "An unexpected internal server error occurred";
  let details: any = null;

  // If it's an expected operational domain exception, unpack it
  if (error instanceof HttpException) {
    statusCode = error.statusCode;
    message = error.message;
    details = error.details;
  } else {
    // Log unexpected code crashes securely for internal diagnostics (Sentry, CloudWatch)
    console.error("💥 Critical Uncaught Application Exception:", error);
  }

  res.status(statusCode).json({
    success: false,
    message,
    ...(details && { details }), // Validation details array if generated by Zod
    timestamp: new Date().toISOString(),
  });
}
