import type { Request, Response, NextFunction } from "express";
import { HttpException } from "@/utils/http.exception";

export function errorMiddleware(error: Error, req: Request, res: Response, _next: NextFunction): void {
  let statusCode = 500;
  let message = "An unexpected internal server error occurred";
  let details: unknown = null;

  // If it's an expected operational domain exception, unpack it.
  if (error instanceof HttpException) {
    statusCode = error.statusCode;
    message = error.message;
    details = error.details;
  }

  // pino-http attaches a per-request child logger (tagged with a request id).
  const log = req.log;

  // Log every server-side failure (5xx) with the full error — including the
  // preserved `cause` chain — so nothing is silently swallowed. Client errors
  // (4xx) are expected/operational and already captured by request logging.
  if (statusCode >= 500) {
    log.error({ err: error, method: req.method, url: req.url }, "💥 Request failed");
  }

  res.status(statusCode).json({
    success: false,
    message,
    ...(details !== null ? { details } : {}), // Validation details array if generated by Zod
    timestamp: new Date().toISOString(),
  });
}
